// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hello.proto

//命名空间

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MicroHello service

type MicroHelloService interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type microHelloService struct {
	c    client.Client
	name string
}

func NewMicroHelloService(name string, c client.Client) MicroHelloService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "hello"
	}
	return &microHelloService{
		c:    c,
		name: name,
	}
}

func (c *microHelloService) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "MicroHello.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MicroHello service

type MicroHelloHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterMicroHelloHandler(s server.Server, hdlr MicroHelloHandler, opts ...server.HandlerOption) error {
	type microHello interface {
		Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error
	}
	type MicroHello struct {
		microHello
	}
	h := &microHelloHandler{hdlr}
	return s.Handle(s.NewHandler(&MicroHello{h}, opts...))
}

type microHelloHandler struct {
	MicroHelloHandler
}

func (h *microHelloHandler) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.MicroHelloHandler.Hello(ctx, in, out)
}
